/**
 * Static dataset of all train lines and their stations available on e-housing.jp.
 * Extracted from e-housing's filter UI. Each line has an ID and an array of stations,
 * each with their own ID and name. These IDs correspond to the `station` and `sname`
 * query parameters used in e-housing search URLs.
 */

export type StationEntry = {
  id: number
  name: string
}

export type TrainLineEntry = {
  id: number
  name: string
  stations: StationEntry[]
}

export const TRAIN_LINES: TrainLineEntry[] = [
  { id: 1, name: 'Mita Line', stations: [{ id: 1, name: 'Meguro' }, { id: 2, name: 'Shirokanedai' }, { id: 3, name: 'Shirokane-takanawa' }, { id: 4, name: 'Mita' }, { id: 5, name: 'Shibakoen' }, { id: 6, name: 'Onarimon' }, { id: 7, name: 'Uchisaiwaicho' }, { id: 8, name: 'Hibiya' }, { id: 9, name: 'Otemachi' }, { id: 10, name: 'Jimbocho' }, { id: 11, name: 'Suidobashi' }, { id: 12, name: 'Kasuga' }, { id: 13, name: 'Hakusan' }, { id: 14, name: 'Sengoku' }, { id: 15, name: 'Sugamo' }, { id: 16, name: 'Nishisugamo' }, { id: 17, name: 'Shin-itabashi' }, { id: 18, name: 'Itabashi-kuyakushomae' }, { id: 19, name: 'Itabashihoncho' }, { id: 20, name: 'Motohasunuma' }, { id: 21, name: 'Shimura-sakaue' }, { id: 22, name: 'Shimura-sanchome' }, { id: 23, name: 'Hasune' }, { id: 24, name: 'Nishidai' }, { id: 25, name: 'Takashimadaira' }, { id: 26, name: 'Shin-takashimadaira' }, { id: 27, name: 'Nishi-takashimadaira' }] },
  { id: 28, name: 'Oedo Line', stations: [{ id: 28, name: 'Hikarigaoka' }, { id: 29, name: 'Nerima-kasugacho' }, { id: 30, name: 'Toshimaen' }, { id: 31, name: 'Nerima' }, { id: 32, name: 'Shin-egota' }, { id: 33, name: 'Ochiai-minami-nagasaki' }, { id: 34, name: 'Nakai' }, { id: 35, name: 'Higashi-Nakano' }, { id: 36, name: 'Nakano-sakaue' }, { id: 37, name: 'Nishi-shinjuku-gochome' }, { id: 38, name: 'Tochomae' }, { id: 39, name: 'Shinjuku' }, { id: 40, name: 'Yoyogi' }, { id: 41, name: 'Kokuritsu-kyogijo' }, { id: 42, name: 'Aoyama-itchome' }, { id: 43, name: 'Roppongi' }, { id: 44, name: 'Azabu-juban' }, { id: 45, name: 'Akabanebashi' }, { id: 46, name: 'Daimon' }, { id: 47, name: 'Shiodome' }, { id: 48, name: 'Tsukijishijo' }, { id: 49, name: 'Kachidoki' }, { id: 50, name: 'Tsukishima' }, { id: 51, name: 'Monzen-nakacho' }, { id: 52, name: 'Kiyosumi-shirakawa' }, { id: 53, name: 'Morishita' }, { id: 54, name: 'Ryogoku' }, { id: 55, name: 'Kuramae' }, { id: 56, name: 'Shin-okachimachi' }, { id: 57, name: 'Ueno-okachimachi' }, { id: 58, name: 'Hongo-sanchome' }, { id: 12, name: 'Kasuga' }, { id: 59, name: 'Iidabashi' }, { id: 60, name: 'Ushigome-kagurazaka' }, { id: 61, name: 'Ushigome-yanagicho' }, { id: 62, name: 'Wakamatsu-kawada' }, { id: 63, name: 'Higashi-shinjuku' }, { id: 64, name: 'Shinjuku-nishiguchi' }] },
  { id: 39, name: 'Shinjuku Line', stations: [{ id: 39, name: 'Shinjuku' }, { id: 65, name: 'Shinjuku-sanchome' }, { id: 66, name: 'Akebonobashi' }, { id: 67, name: 'Ichigaya' }, { id: 68, name: 'Kudanshita' }, { id: 69, name: 'Jinbocho' }, { id: 70, name: 'Ogawamachi' }, { id: 71, name: 'Iwamotocho' }, { id: 72, name: 'Bakuro-yokoyama' }, { id: 73, name: 'Hamacho' }, { id: 53, name: 'Morishita' }, { id: 74, name: 'Kikukawa' }, { id: 75, name: 'Sumiyoshi' }, { id: 76, name: 'Nishi-ojima' }, { id: 77, name: 'Ojima' }, { id: 78, name: 'Higashi-ojima' }, { id: 79, name: 'Funabori' }, { id: 80, name: 'Ichinoe' }, { id: 81, name: 'Mizue' }, { id: 82, name: 'Shinozaki' }, { id: 83, name: 'Motoyawata' }, { id: 10, name: 'Jimbocho' }] },
  { id: 84, name: 'Asakusa Line', stations: [{ id: 84, name: 'Nishi-magome' }, { id: 85, name: 'Magome' }, { id: 86, name: 'Nakanobu' }, { id: 87, name: 'Togoshi' }, { id: 88, name: 'Gotanda' }, { id: 89, name: 'Takanawadai' }, { id: 90, name: 'Sengakuji' }, { id: 4, name: 'Mita' }, { id: 46, name: 'Daimon' }, { id: 91, name: 'Shinbashi' }, { id: 92, name: 'Higashi-ginza' }, { id: 93, name: 'Takaracho' }, { id: 94, name: 'Nihombashi' }, { id: 95, name: 'Ningyocho' }, { id: 96, name: 'Higashi-nihombashi' }, { id: 97, name: 'Asakusabashi' }, { id: 55, name: 'Kuramae' }, { id: 98, name: 'Asakusa' }, { id: 99, name: 'Honjo-azumabashi' }, { id: 100, name: 'Oshiage' }] },
  { id: 101, name: 'Ginza Line', stations: [{ id: 101, name: 'Shibuya' }, { id: 102, name: 'Omotesando' }, { id: 103, name: 'Gaiemmae' }, { id: 42, name: 'Aoyama-itchome' }, { id: 104, name: 'Akasaka-mitsuke' }, { id: 105, name: 'Tameike-sanno' }, { id: 106, name: 'Toranomon' }, { id: 91, name: 'Shinbashi' }, { id: 107, name: 'Ginza' }, { id: 108, name: 'Kyobashi' }, { id: 94, name: 'Nihombashi' }, { id: 109, name: 'Mitsukoshimae' }, { id: 110, name: 'Kanda' }, { id: 111, name: 'Suehirocho' }, { id: 112, name: 'Ueno-hirokoji' }, { id: 113, name: 'Ueno' }, { id: 114, name: 'Inaricho' }, { id: 115, name: 'Tawaramachi' }, { id: 98, name: 'Asakusa' }] },
  { id: 116, name: 'Marunouchi Line', stations: [{ id: 116, name: 'Ogikubo' }, { id: 117, name: 'Minami-asagaya' }, { id: 118, name: 'Shin-koenji' }, { id: 119, name: 'Higashi-koenji' }, { id: 120, name: 'Shin-nakano' }, { id: 36, name: 'Nakano-sakaue' }, { id: 121, name: 'Nishi-shinjuku' }, { id: 39, name: 'Shinjuku' }, { id: 65, name: 'Shinjuku-sanchome' }, { id: 122, name: 'Shinjuku-gyoemmae' }, { id: 123, name: 'Yotsuya-sanchome' }, { id: 124, name: 'Yotsuya' }, { id: 104, name: 'Akasaka-mitsuke' }, { id: 125, name: 'Kokkai-gijidomae' }, { id: 126, name: 'Kasumigaseki' }, { id: 107, name: 'Ginza' }, { id: 127, name: 'Tokyo' }, { id: 9, name: 'Otemachi' }, { id: 128, name: 'Awajicho' }, { id: 129, name: 'Ochanomizu' }, { id: 58, name: 'Hongo-sanchome' }, { id: 130, name: 'Korakuen' }, { id: 131, name: 'Myogadani' }, { id: 132, name: 'Shin-otsuka' }, { id: 133, name: 'Ikebukuro' }, { id: 134, name: 'Nakano-shimbashi' }, { id: 135, name: 'Nakano-fujimicho' }, { id: 136, name: 'Honancho' }] },
  { id: 137, name: 'Hibiya Line', stations: [{ id: 137, name: 'Nakameguro' }, { id: 138, name: 'Ebisu' }, { id: 139, name: 'Hiroo' }, { id: 43, name: 'Roppongi' }, { id: 140, name: 'Kamiyacho' }, { id: 141, name: 'Toranomon Hills' }, { id: 126, name: 'Kasumigaseki' }, { id: 8, name: 'Hibiya' }, { id: 107, name: 'Ginza' }, { id: 92, name: 'Higashi-ginza' }, { id: 142, name: 'Tsukiji' }, { id: 143, name: 'Hatchobori' }, { id: 144, name: 'Kayabacho' }, { id: 95, name: 'Ningyocho' }, { id: 145, name: 'Kodemmacho' }, { id: 146, name: 'Akihabara' }, { id: 147, name: 'Naka-okachimachi' }, { id: 113, name: 'Ueno' }, { id: 148, name: 'Iriya' }, { id: 149, name: 'Minowa' }, { id: 150, name: 'Minami-senju' }, { id: 151, name: 'Kita-senju' }] },
  { id: 152, name: 'Tozai Line', stations: [{ id: 152, name: 'Nakano' }, { id: 153, name: 'Ochiai' }, { id: 154, name: 'Takadanobaba' }, { id: 155, name: 'Waseda' }, { id: 156, name: 'Kagurazaka' }, { id: 59, name: 'Iidabashi' }, { id: 68, name: 'Kudanshita' }, { id: 157, name: 'Takebashi' }, { id: 9, name: 'Otemachi' }, { id: 94, name: 'Nihombashi' }, { id: 144, name: 'Kayabacho' }, { id: 51, name: 'Monzen-nakacho' }, { id: 158, name: 'Kiba' }, { id: 159, name: 'Toyocho' }, { id: 160, name: 'Minami-sunamachi' }, { id: 161, name: 'Nishi-kasai' }, { id: 162, name: 'Kasai' }, { id: 163, name: 'Urayasu' }, { id: 164, name: 'Minami-gyotoku' }, { id: 165, name: 'Gyotoku' }, { id: 166, name: 'Myoden' }, { id: 167, name: 'Baraki-nakayama' }, { id: 168, name: 'Nishi-funabashi' }] },
  { id: 169, name: 'Chiyoda Line', stations: [{ id: 169, name: 'Yoyogi-Uehara' }, { id: 170, name: 'Yoyogi Koen' }, { id: 171, name: 'Meiji-jingumae' }, { id: 102, name: 'Omotesando' }, { id: 172, name: 'Nogizaka' }, { id: 173, name: 'Akasaka' }, { id: 125, name: 'Kokkai-gijidomae' }, { id: 126, name: 'Kasumigaseki' }, { id: 8, name: 'Hibiya' }, { id: 174, name: 'Nijubashimae' }, { id: 9, name: 'Otemachi' }, { id: 175, name: 'Shin-ochanomizu' }, { id: 176, name: 'Yushima' }, { id: 177, name: 'Nezu' }, { id: 178, name: 'Sendagi' }, { id: 179, name: 'Nishi-nippori' }, { id: 180, name: 'Machiya' }, { id: 151, name: 'Kita-senju' }, { id: 181, name: 'Ayase' }, { id: 182, name: 'Kita-ayase' }] },
  { id: 183, name: 'Yurakucho Line', stations: [{ id: 183, name: 'Wakoshi' }, { id: 184, name: 'Chikatetsu-narimasu' }, { id: 185, name: 'Chikatetsu-akatsuka' }, { id: 186, name: 'Heiwadai' }, { id: 187, name: 'Hikawadai' }, { id: 188, name: 'Senkawa' }, { id: 189, name: 'Kanamecho' }, { id: 133, name: 'Ikebukuro' }, { id: 190, name: 'Higashi-Ikebukuro' }, { id: 191, name: 'Gokokuji' }, { id: 192, name: 'Edogawabashi' }, { id: 59, name: 'Iidabashi' }, { id: 67, name: 'Ichigaya' }, { id: 193, name: 'Kojimachi' }, { id: 194, name: 'Nagatacho' }, { id: 195, name: 'Sakuradamon' }, { id: 196, name: 'Yurakucho' }, { id: 197, name: 'Ginza-itchome' }, { id: 198, name: 'Shintomicho' }, { id: 50, name: 'Tsukishima' }, { id: 199, name: 'Toyosu' }, { id: 200, name: 'Tatsumi' }, { id: 201, name: 'Shin-Kiba' }, { id: 202, name: 'Shinsakuradai' }, { id: 215, name: 'Kotake-mukaihara' }] },
  { id: 203, name: 'Nanboku Line', stations: [{ id: 203, name: 'Akabane-iwabuchi' }, { id: 204, name: 'Shimo' }, { id: 205, name: 'Oji-kamiya' }, { id: 206, name: 'Oji' }, { id: 207, name: 'Nishigahara' }, { id: 208, name: 'Komagome' }, { id: 209, name: 'Hon-komagome' }, { id: 210, name: 'Todaimae' }, { id: 130, name: 'Korakuen' }, { id: 59, name: 'Iidabashi' }, { id: 67, name: 'Ichigaya' }, { id: 124, name: 'Yotsuya' }, { id: 194, name: 'Nagatacho' }, { id: 105, name: 'Tameike-sanno' }, { id: 211, name: 'Roppongi-itchome' }, { id: 44, name: 'Azabu-juban' }, { id: 3, name: 'Shirokane-takanawa' }, { id: 2, name: 'Shirokanedai' }, { id: 1, name: 'Meguro' }] },
  { id: 101, name: 'Fukutoshin Line', stations: [{ id: 101, name: 'Shibuya' }, { id: 171, name: 'Meiji-jingumae' }, { id: 212, name: 'Kitasando' }, { id: 65, name: 'Shinjuku-sanchome' }, { id: 63, name: 'Higashi-shinjuku' }, { id: 213, name: 'Nishi-waseda' }, { id: 214, name: 'Zoshigaya' }, { id: 133, name: 'Ikebukuro' }, { id: 189, name: 'Kanamecho' }, { id: 188, name: 'Senkawa' }, { id: 215, name: 'Kotake-mukaihara' }, { id: 187, name: 'Hikawadai' }, { id: 186, name: 'Heiwadai' }, { id: 185, name: 'Chikatetsu-akatsuka' }, { id: 184, name: 'Chikatetsu-narimasu' }, { id: 183, name: 'Wakoshi' }] },
  { id: 101, name: 'Hanzomon Line', stations: [{ id: 101, name: 'Shibuya' }, { id: 102, name: 'Omotesando' }, { id: 42, name: 'Aoyama-itchome' }, { id: 194, name: 'Nagatacho' }, { id: 216, name: 'Hanzomon' }, { id: 68, name: 'Kudanshita' }, { id: 69, name: 'Jinbocho' }, { id: 9, name: 'Otemachi' }, { id: 109, name: 'Mitsukoshimae' }, { id: 217, name: 'Suitengumae' }, { id: 52, name: 'Kiyosumi-shirakawa' }, { id: 75, name: 'Sumiyoshi' }, { id: 218, name: 'Kinshicho' }, { id: 100, name: 'Oshiage' }, { id: 10, name: 'Jimbocho' }] },
  { id: 127, name: 'Yokosuka Line', stations: [{ id: 127, name: 'Tokyo' }, { id: 91, name: 'Shinbashi' }, { id: 219, name: 'Shinagawa' }, { id: 220, name: 'Nishioi' }, { id: 221, name: 'Musashi Kosugi' }, { id: 222, name: 'Shin-Kawasaki' }, { id: 223, name: 'Yokohama' }, { id: 224, name: 'Hodogaya' }, { id: 225, name: 'Higashitotsuka' }, { id: 226, name: 'Totsuka' }, { id: 227, name: 'Ofune' }, { id: 228, name: 'Kita Kamakura' }, { id: 229, name: 'Kamakura' }, { id: 230, name: 'Zushi' }, { id: 231, name: 'Higashizushi' }, { id: 232, name: 'Taura' }, { id: 233, name: 'Yokosuka' }, { id: 234, name: 'Kinugasa' }, { id: 235, name: 'Kurihama' }] },
  { id: 236, name: 'Keihin-Tohoku Line', stations: [{ id: 236, name: 'Akabane' }, { id: 237, name: 'Higashijujo' }, { id: 206, name: 'Oji' }, { id: 238, name: 'Kaminakazato' }, { id: 239, name: 'Tabata' }, { id: 179, name: 'Nishi-nippori' }, { id: 240, name: 'Nippori' }, { id: 241, name: 'Uguisudani' }, { id: 113, name: 'Ueno' }, { id: 242, name: 'Okachimachi' }, { id: 146, name: 'Akihabara' }, { id: 110, name: 'Kanda' }, { id: 127, name: 'Tokyo' }, { id: 196, name: 'Yurakucho' }, { id: 91, name: 'Shinbashi' }, { id: 243, name: 'Hamamatsucho' }, { id: 244, name: 'Tamachi' }, { id: 245, name: 'Takanawa Gateway' }, { id: 219, name: 'Shinagawa' }, { id: 246, name: 'Oimachi' }, { id: 247, name: 'Omori' }, { id: 248, name: 'Kamata' }, { id: 249, name: 'Kawasaki' }, { id: 250, name: 'Tsurumi' }, { id: 251, name: 'Shinkoyasu' }, { id: 252, name: 'Higashi-kanagawa' }, { id: 223, name: 'Yokohama' }, { id: 253, name: 'Sakuragicho' }, { id: 254, name: 'Kannai' }, { id: 255, name: 'Ishikawachoo' }, { id: 256, name: 'Yamate' }, { id: 257, name: 'Negishi' }, { id: 227, name: 'Ofune' }, { id: 258, name: 'Kawaguchi' }, { id: 259, name: 'Nishikawaguchi' }, { id: 260, name: 'Warabi' }, { id: 261, name: 'Minami Urawa' }, { id: 262, name: 'Urawa' }, { id: 263, name: 'Kita-urawa' }, { id: 264, name: 'Yono' }, { id: 265, name: 'Saitama-Shintoshin' }, { id: 266, name: 'Omiya' }, { id: 584, name: 'Konandai' }] },
  { id: 267, name: 'Saikyo Line', stations: [{ id: 267, name: 'Osaki' }, { id: 138, name: 'Ebisu' }, { id: 101, name: 'Shibuya' }, { id: 39, name: 'Shinjuku' }, { id: 133, name: 'Ikebukuro' }, { id: 268, name: 'Itabashi' }, { id: 269, name: 'Jujo' }, { id: 236, name: 'Akabane' }, { id: 270, name: 'Kitaakabane' }, { id: 271, name: 'Ukimafunato' }, { id: 272, name: 'Toda-koen' }, { id: 273, name: 'Toda' }, { id: 274, name: 'Kita Toda' }, { id: 275, name: 'Musashi-urawa' }, { id: 276, name: 'Nakaurawa' }, { id: 277, name: 'Minamiyono' }, { id: 278, name: 'Yonohonmachi' }, { id: 279, name: 'Kitayono' }, { id: 266, name: 'Omiya' }, { id: 220, name: 'Nishioi' }] },
  { id: 280, name: 'Sobu Line', stations: [{ id: 280, name: 'Mitaka' }, { id: 281, name: 'Kichijoji' }, { id: 282, name: 'Nishi-Ogikubo' }, { id: 116, name: 'Ogikubo' }, { id: 283, name: 'Asagaya' }, { id: 284, name: 'Koenji' }, { id: 152, name: 'Nakano' }, { id: 35, name: 'Higashi-Nakano' }, { id: 285, name: 'Okubo' }, { id: 286, name: 'Shinanomachi' }, { id: 67, name: 'Ichigaya' }, { id: 59, name: 'Iidabashi' }, { id: 11, name: 'Suidobashi' }, { id: 127, name: 'Tokyo' }, { id: 287, name: 'Shin Nihonbashi' }, { id: 288, name: 'Bakurocho' }, { id: 129, name: 'Ochanomizu' }, { id: 146, name: 'Akihabara' }, { id: 97, name: 'Asakusabashi' }, { id: 54, name: 'Ryogoku' }, { id: 218, name: 'Kinshicho' }, { id: 289, name: 'Kameido' }, { id: 290, name: 'Hirai' }, { id: 291, name: 'Shinkoiwa' }, { id: 292, name: 'Koiwa' }, { id: 293, name: 'Ichikawa' }, { id: 83, name: 'Motoyawata' }, { id: 294, name: 'Shimousa Nakayama' }, { id: 295, name: 'Nishifunabashi' }, { id: 296, name: 'Funabashi' }, { id: 297, name: 'Higashi Funabashi' }, { id: 298, name: 'Tsudanuma' }, { id: 299, name: 'Makuhari Hongo' }, { id: 300, name: 'Makuhari' }, { id: 301, name: 'Shin-Kemigawa' }, { id: 302, name: 'Inage' }, { id: 303, name: 'Nishi-Chiba' }, { id: 304, name: 'Chiba' }, { id: 39, name: 'Shinjuku' }, { id: 40, name: 'Yoyogi' }, { id: 124, name: 'Yotsuya' }, { id: 168, name: 'Nishi-funabashi' }, { id: 309, name: 'Sendagaya' }] },
  { id: 127, name: 'Yamanote Line', stations: [{ id: 127, name: 'Tokyo' }, { id: 196, name: 'Yurakucho' }, { id: 91, name: 'Shinbashi' }, { id: 243, name: 'Hamamatsucho' }, { id: 244, name: 'Tamachi' }, { id: 245, name: 'Takanawa Gateway' }, { id: 219, name: 'Shinagawa' }, { id: 267, name: 'Osaki' }, { id: 88, name: 'Gotanda' }, { id: 1, name: 'Meguro' }, { id: 138, name: 'Ebisu' }, { id: 101, name: 'Shibuya' }, { id: 305, name: 'Harajuku' }, { id: 40, name: 'Yoyogi' }, { id: 39, name: 'Shinjuku' }, { id: 306, name: 'Shin Okubo' }, { id: 154, name: 'Takadanobaba' }, { id: 307, name: 'Mejiro' }, { id: 133, name: 'Ikebukuro' }, { id: 308, name: 'Otsuka' }, { id: 15, name: 'Sugamo' }, { id: 208, name: 'Komagome' }, { id: 239, name: 'Tabata' }, { id: 179, name: 'Nishi-nippori' }, { id: 240, name: 'Nippori' }, { id: 241, name: 'Uguisudani' }, { id: 113, name: 'Ueno' }, { id: 242, name: 'Okachimachi' }, { id: 146, name: 'Akihabara' }, { id: 110, name: 'Kanda' }] },
  { id: 127, name: 'Chuo Line', stations: [{ id: 127, name: 'Tokyo' }, { id: 110, name: 'Kanda' }, { id: 129, name: 'Ochanomizu' }, { id: 11, name: 'Suidobashi' }, { id: 59, name: 'Iidabashi' }, { id: 67, name: 'Ichigaya' }, { id: 124, name: 'Yotsuya' }, { id: 286, name: 'Shinanomachi' }, { id: 309, name: 'Sendagaya' }, { id: 40, name: 'Yoyogi' }, { id: 39, name: 'Shinjuku' }, { id: 285, name: 'Okubo' }, { id: 35, name: 'Higashi-Nakano' }, { id: 152, name: 'Nakano' }, { id: 284, name: 'Koenji' }, { id: 283, name: 'Asagaya' }, { id: 116, name: 'Ogikubo' }, { id: 282, name: 'Nishi-Ogikubo' }, { id: 281, name: 'Kichijoji' }, { id: 280, name: 'Mitaka' }, { id: 310, name: 'Musashisakai' }, { id: 311, name: 'Higashi-Koganei' }, { id: 312, name: 'Musashi Koganei' }, { id: 313, name: 'Kokubunji' }, { id: 314, name: 'Nishi Kokubunji' }, { id: 315, name: 'Kunitachi' }, { id: 316, name: 'Tachikawa' }, { id: 317, name: 'Hino' }, { id: 318, name: 'Toyota' }, { id: 319, name: 'Hachioji' }, { id: 320, name: 'Nishihachioji' }, { id: 321, name: 'Takao' }] },
  { id: 101, name: 'Toyoko Line', stations: [{ id: 101, name: 'Shibuya' }, { id: 322, name: 'Daikanyama' }, { id: 137, name: 'Nakameguro' }, { id: 323, name: 'Yutenji' }, { id: 324, name: 'Gakugei-daigaku' }, { id: 325, name: 'Toritsu-daigaku' }, { id: 326, name: 'Jiyugaoka' }, { id: 327, name: 'Den-en-Chofu' }, { id: 328, name: 'Tamagawa' }, { id: 329, name: 'Shin-Maruko' }, { id: 330, name: 'Musashi-Kosugi' }, { id: 331, name: 'Motosumiyoshi' }, { id: 332, name: 'Hiyoshi' }, { id: 333, name: 'Tsunashima' }, { id: 334, name: 'Okurayama' }, { id: 335, name: 'Kikuna' }, { id: 336, name: 'Myorenji' }, { id: 337, name: 'Hakuraku' }, { id: 338, name: 'Higashi-Hakuraku' }, { id: 339, name: 'Tammachi' }, { id: 223, name: 'Yokohama' }, { id: 221, name: 'Musashi Kosugi' }] },
  { id: 1, name: 'Meguro Line', stations: [{ id: 1, name: 'Meguro' }, { id: 340, name: 'Fudomae' }, { id: 341, name: 'Musashi-Koyama' }, { id: 342, name: 'Nishi-Koyama' }, { id: 343, name: 'Senzoku' }, { id: 344, name: 'Ookayama' }, { id: 345, name: 'Okusawa' }, { id: 327, name: 'Den-en-Chofu' }, { id: 328, name: 'Tamagawa' }, { id: 329, name: 'Shin-Maruko' }, { id: 330, name: 'Musashi-Kosugi' }, { id: 331, name: 'Motosumiyoshi' }, { id: 332, name: 'Hiyoshi' }] },
  { id: 101, name: 'Den-en-toshi Line', stations: [{ id: 101, name: 'Shibuya' }, { id: 346, name: 'Ikejiri-Ohashi' }, { id: 347, name: 'Sangen-Jaya' }, { id: 348, name: 'Komazawa-Daigaku' }, { id: 349, name: 'Sakura-Shinmachi' }, { id: 350, name: 'Yoga' }, { id: 351, name: 'Futako-Tamagawa' }, { id: 352, name: 'Futako-Shinchi' }, { id: 353, name: 'Takatsu' }, { id: 354, name: 'Mizonokuchi' }, { id: 355, name: 'Kajigaya' }, { id: 356, name: 'Miyazakidai' }, { id: 357, name: 'Miyamaedaira' }, { id: 358, name: 'Saginuma' }, { id: 359, name: 'Tama-Plaza' }, { id: 360, name: 'Azamino' }, { id: 361, name: 'Eda' }, { id: 362, name: 'Ichigao' }, { id: 363, name: 'Fujigaoka' }, { id: 364, name: 'Aobadai' }, { id: 365, name: 'Tana' }, { id: 366, name: 'Nagatsuta' }, { id: 367, name: 'Tsukushino' }, { id: 368, name: 'Suzukakedai' }, { id: 369, name: 'Minami-Machida' }, { id: 370, name: 'Tsukimino' }, { id: 371, name: 'Chuo-Rinkan' }] },
  { id: 351, name: 'Oimachi Line', stations: [{ id: 351, name: 'Futako-Tamagawa' }, { id: 372, name: 'Kaminoge' }, { id: 373, name: 'Todoroki' }, { id: 374, name: 'Oyamadai' }, { id: 375, name: 'Kuhonbutsu' }, { id: 326, name: 'Jiyugaoka' }, { id: 376, name: 'Midorigaoka' }, { id: 344, name: 'Ookayama' }, { id: 377, name: 'Kita-Senzoku' }, { id: 378, name: 'Hatanodai' }, { id: 379, name: 'Ebaranishi' }, { id: 86, name: 'Nakanobu' }, { id: 380, name: 'Togoshi-Koen' }, { id: 381, name: 'Shimomeguro' }, { id: 246, name: 'Oimachi' }, { id: 352, name: 'Futako-Shinchi' }, { id: 353, name: 'Takatsu' }, { id: 354, name: 'Mizonokuchi' }] },
  { id: 88, name: 'Ikegami Line', stations: [{ id: 88, name: 'Gotanda' }, { id: 382, name: 'Osaki-Hirokoji' }, { id: 383, name: 'Togoshi-Ginza' }, { id: 384, name: 'Ebara-Nakanobu' }, { id: 378, name: 'Hatanodai' }, { id: 385, name: 'Nagahara' }, { id: 386, name: 'Senzokuike' }, { id: 387, name: 'Ishikawadai' }, { id: 388, name: 'Yukigaya-Otsuka' }, { id: 389, name: 'Ontakesan' }, { id: 390, name: 'Kugahara' }, { id: 391, name: 'Chidoricho' }, { id: 392, name: 'Ikegami' }, { id: 393, name: 'Hasunuma' }, { id: 248, name: 'Kamata' }] },
  { id: 223, name: 'Minatomirai Line', stations: [{ id: 223, name: 'Yokohama' }, { id: 394, name: 'Shintakashima' }, { id: 395, name: 'Minatomirai' }, { id: 396, name: 'Bashamichi' }, { id: 397, name: 'Nihon-odori' }, { id: 398, name: 'Motomachi-Chukagai' }] },
  { id: 39, name: 'Keio Line', stations: [{ id: 39, name: 'Shinjuku' }, { id: 399, name: 'Sasazuka' }, { id: 400, name: 'Daitabashi' }, { id: 401, name: 'Meidaimae' }, { id: 402, name: 'Shimotakaido' }, { id: 403, name: 'Sakurajosui' }, { id: 404, name: 'Kamikitazawa' }, { id: 405, name: 'Hachimanyama' }, { id: 406, name: 'Rokakoen' }, { id: 407, name: 'Chitose-Karasuyama' }, { id: 408, name: 'Sengawa' }, { id: 409, name: 'Tsutsujigaoka' }, { id: 410, name: 'Shibasaki' }, { id: 580, name: 'Keio-Nagayama' }, { id: 590, name: 'Hatagaya' }, { id: 592, name: 'Kita-Fuchu' }, { id: 593, name: 'Fuchu' }, { id: 595, name: 'Higashi-Fuchu' }] },
  { id: 101, name: 'Inokashira Line', stations: [{ id: 101, name: 'Shibuya' }, { id: 411, name: 'Shinsen' }, { id: 412, name: 'Komaba-todaimae' }, { id: 413, name: 'Ikenoue' }, { id: 414, name: 'Shimokitazawa' }, { id: 415, name: 'Shindaita' }, { id: 416, name: 'Higashi-matsubara' }, { id: 401, name: 'Meidaimae' }, { id: 417, name: 'Eifukucho' }, { id: 418, name: 'Nishi-eifuku' }, { id: 419, name: 'Hamadayama' }, { id: 420, name: 'Takaido' }, { id: 421, name: 'Fujimigaoka' }, { id: 422, name: 'Kugayama' }, { id: 423, name: 'Mitakadai' }, { id: 424, name: 'Inokashira-koen' }, { id: 281, name: 'Kichijoji' }] },
  { id: 39, name: 'Odakyu Line', stations: [{ id: 39, name: 'Shinjuku' }, { id: 425, name: 'Minami-Shinjuku' }, { id: 426, name: 'Sangubashi' }, { id: 427, name: 'Yoyogi-Hachiman' }, { id: 169, name: 'Yoyogi-Uehara' }, { id: 428, name: 'Higashi-Kitazawa' }, { id: 414, name: 'Shimokitazawa' }, { id: 429, name: 'Setagaya-Daita' }, { id: 430, name: 'Umegaoka' }, { id: 431, name: 'Gotokuji' }, { id: 432, name: 'Kyodo' }, { id: 433, name: 'Chitose-Funabashi' }, { id: 434, name: 'Soshigaya-Okura' }, { id: 435, name: 'Seijogakuen-mae' }, { id: 436, name: 'Kitami' }, { id: 437, name: 'Komae' }, { id: 438, name: 'Izumi-Tamagawa' }, { id: 439, name: 'Noborito' }, { id: 440, name: 'Mukogaoka-Yuen' }, { id: 441, name: 'Ikuta' }, { id: 442, name: 'Yomiuriland-mae' }, { id: 443, name: 'Yurigaoka' }, { id: 444, name: 'Shin-Yurigaoka' }, { id: 445, name: 'Kakio' }, { id: 446, name: 'Tsurukawa' }, { id: 447, name: 'Tamagawagakuen-mae' }, { id: 448, name: 'Machida' }, { id: 449, name: 'Sagami-Ono' }, { id: 450, name: 'Odakyu-Sagamihara' }, { id: 451, name: 'Sobudaimae' }, { id: 452, name: 'Zama' }, { id: 453, name: 'Ebina' }, { id: 454, name: 'Atsugi' }, { id: 455, name: 'Hon-Atsugi' }, { id: 456, name: 'Aiko-Ishida' }, { id: 457, name: 'Isehara' }, { id: 458, name: 'Tsurumaki-Onsen' }, { id: 459, name: 'Tokai-Daigaku-mae' }, { id: 460, name: 'Hadano' }, { id: 461, name: 'Shin-Matsuda' }, { id: 462, name: 'Odawara' }, { id: 463, name: 'Hakone-Yumoto' }, { id: 581, name: 'Odakyu-Nagayama' }] },
  { id: 464, name: 'Seibu-Shinjuku Line', stations: [{ id: 464, name: 'Seibu Shinjuku' }, { id: 154, name: 'Takadanobaba' }, { id: 465, name: 'Shimo-Ochiai' }, { id: 34, name: 'Nakai' }, { id: 466, name: 'Arai Yakushimae' }, { id: 467, name: 'Numabukuro' }, { id: 468, name: 'Nogata' }, { id: 469, name: 'Toritsu Kasei' }, { id: 470, name: 'Saginomiya' }, { id: 471, name: 'Shimo-Igusa' }, { id: 472, name: 'Iogi' }, { id: 473, name: 'Kami-Igusa' }, { id: 474, name: 'Kami-Shakujii' }, { id: 475, name: 'Musashi-Seki' }, { id: 476, name: 'Higashi-Fushimi' }, { id: 477, name: 'Seibu Yanagisawa' }, { id: 478, name: 'Tanashi' }, { id: 479, name: 'Hana-Koganei' }, { id: 480, name: 'Kodaira' }, { id: 481, name: 'Kumegawa' }, { id: 482, name: 'Higashi-Murayama' }, { id: 483, name: 'Tokorozawa' }, { id: 484, name: 'Koku-Koen' }, { id: 485, name: 'Shin-Tokorozawa' }, { id: 486, name: 'Iruma' }, { id: 487, name: 'Sayama-shi' }, { id: 488, name: 'Shin-Sayama' }, { id: 489, name: 'Minami-Otsuka' }, { id: 490, name: 'Hon-Kawagoe' }] },
  { id: 201, name: 'Rinkai Line', stations: [{ id: 201, name: 'Shin-Kiba' }, { id: 514, name: 'Shinonome' }, { id: 515, name: 'Kokusai-Tenjijo' }, { id: 516, name: 'Tokyo Teleport' }, { id: 505, name: 'Tennozu Isle' }, { id: 517, name: 'Shinagawa Seaside' }, { id: 246, name: 'Oimachi' }, { id: 267, name: 'Osaki' }] },
  { id: 90, name: 'Keikyu Main Line', stations: [{ id: 90, name: 'Sengakuji' }, { id: 219, name: 'Shinagawa' }, { id: 518, name: 'Kitashinagawa' }, { id: 519, name: 'Shimbamba' }, { id: 520, name: 'Aomonoyokocho' }, { id: 521, name: 'Samezu' }, { id: 522, name: 'Tachiaigawa' }, { id: 523, name: 'Omori Kaigan' }, { id: 524, name: 'Ume-yashiki' }, { id: 525, name: 'Keikyu Kamata' }, { id: 526, name: 'Namamugi' }, { id: 527, name: 'Keikyu Shin-Koyasu' }, { id: 528, name: 'Koyasu' }, { id: 529, name: 'Kanagawa-Shimmachi' }, { id: 530, name: 'Keikyu Higashi-Kanagawa' }, { id: 531, name: 'Kanagawa' }, { id: 223, name: 'Yokohama' }, { id: 532, name: 'Tobe' }, { id: 533, name: 'Hinodecho' }, { id: 534, name: 'Koganecho' }, { id: 535, name: 'Minami-Ota' }, { id: 536, name: 'Idogaya' }, { id: 537, name: 'Komyoji' }, { id: 538, name: 'Kamiooka' }, { id: 539, name: 'Byobugaura' }, { id: 540, name: 'Sugita' }, { id: 541, name: 'Keikyu Tomioka' }, { id: 542, name: 'Nokendai' }, { id: 543, name: 'Kanazawa-Bunko' }, { id: 544, name: 'Kanazawa-Hakkei' }, { id: 545, name: 'Oppama' }, { id: 546, name: 'Keikyu Taura' }, { id: 547, name: 'Anjinzuka' }, { id: 549, name: 'Shioiri' }, { id: 548, name: 'Yokosuka-Chuo' }, { id: 550, name: 'Kenritsu-Daigaku' }, { id: 551, name: 'Hori-No-Uchi' }, { id: 552, name: 'Keikyu Otsu' }, { id: 553, name: 'Umagahama-Kaigan' }, { id: 554, name: 'Uraga' }, { id: 572, name: 'Aoto' }, { id: 573, name: 'Ohanachaya' }, { id: 598, name: 'Heiwajima' }, { id: 599, name: 'Omorimachi' }] },
  { id: 582, name: 'Keisei Line', stations: [{ id: 582, name: 'Oedo' }, { id: 594, name: 'Nishifu' }, { id: 595, name: 'Higashi-Fuchu' }] },
  { id: 91, name: 'Tokaido Main Line', stations: [{ id: 91, name: 'Shinbashi' }, { id: 127, name: 'Tokyo' }, { id: 219, name: 'Shinagawa' }, { id: 223, name: 'Yokohama' }, { id: 249, name: 'Kawasaki' }, { id: 588, name: 'Kita-Chigasaki' }, { id: 589, name: 'Hiratsuka' }] },
  { id: 248, name: 'Tamagawa Line', stations: [{ id: 248, name: 'Kamata' }, { id: 328, name: 'Tamagawa' }, { id: 596, name: 'Shimomaruko' }, { id: 597, name: 'Musashi Shinden' }] },
  { id: 600, name: 'JR Yokohama Line', stations: [{ id: 600, name: 'Shin-Yokohama' }] },
]

/**
 * All 32 wards available on e-housing.jp.
 * Can also be fetched live from GET api.e-housing.jp/wards.
 */
export type WardEntry = {
  id: number
  name: string
  slug: string
}

export const WARDS: WardEntry[] = [
  { id: 1, name: 'Minato', slug: 'minato' },
  { id: 2, name: 'Shibuya', slug: 'shibuya' },
  { id: 3, name: 'Shinjuku', slug: 'shinjuku' },
  { id: 4, name: 'Meguro', slug: 'meguro' },
  { id: 5, name: 'Setagaya', slug: 'setagaya' },
  { id: 6, name: 'Chuo', slug: 'chuo' },
  { id: 7, name: 'Bunkyo', slug: 'bunkyo' },
  { id: 8, name: 'Chiyoda', slug: 'chiyoda' },
  { id: 9, name: 'Shinagawa', slug: 'shinagawa' },
  { id: 10, name: 'Nakano', slug: 'nakano' },
  { id: 11, name: 'Suginami', slug: 'suginami' },
  { id: 12, name: 'Ota', slug: 'ota' },
  { id: 13, name: 'Toshima', slug: 'toshima' },
  { id: 14, name: 'Koto', slug: 'koto' },
  { id: 16, name: 'Taito', slug: 'taito' },
  { id: 17, name: 'Arakawa', slug: 'arakawa' },
  { id: 18, name: 'Kita', slug: 'kita' },
  { id: 19, name: 'Sumida', slug: 'sumida' },
  { id: 20, name: 'Nerima', slug: 'nerima' },
  { id: 21, name: 'Itabashi', slug: 'itabashi' },
  { id: 22, name: 'Edogawa', slug: 'edogawa' },
  { id: 24, name: 'Adachi', slug: 'adachi' },
  { id: 25, name: 'Musashi', slug: 'musashi' },
  { id: 26, name: 'Hachioji', slug: 'hachioji' },
  { id: 27, name: 'Tama', slug: 'tama' },
  { id: 28, name: 'Tsuzuki', slug: 'tsuzuki' },
  { id: 29, name: 'Katsushika', slug: 'katsushika' },
  { id: 30, name: 'Machida', slug: 'machida' },
  { id: 31, name: 'Yokohama', slug: 'yokohama' },
  { id: 32, name: 'Chiba', slug: 'chiba' },
  { id: 33, name: 'Kanagawa', slug: 'kanagawa' },
  { id: 34, name: 'Chofu', slug: 'chofu' },
]
